name: dependency_module
description: A new Flutter package project.
publish_to: "none"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: any
  flutter_modular: ^5.0.3
  connectivity_plus: ^2.3.5
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  asuka: ^2.0.0+1
  flutter_triple: ^1.2.7+2
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  lottie: ^1.3.0
  iconly: ^1.0.1
  date_picker_timeline: ^1.2.3
  jwt_decoder: ^2.0.1
